### ISSUE TITLE
Impossible to display public videos

### ISSUE THREAD

**Issue by Adsys12** [veo-labs/openveo-portal#4]
I followed the configuration steps, and I tried a lot of manipulation but without result.
I have 2 videos one in public and the other in private. But I don't know why, the 2 videos are still private.
Can someone help me with this please.
My config is attached

~/.openveo/portal/conf.json (I have used categories ID (Public and Private))
![image](https://user-images.githubusercontent.com/89521201/130780776-a8d581fb-c7ea-41f8-9876-25b2793b7593.png)

Publish catalog
![image](https://user-images.githubusercontent.com/89521201/130780910-160b1e5f-5135-43bd-8d4c-f1da3bbc10d0.png)

**Comment by maxime-beguin** [comment]
Hi @Adsys12,

As specified in the [documentation of the OpenVeo Portal configuration file](https://veo-labs.github.io/openveo-portal/7.0.0/advanced-configuration/), `privateFilter` and `publicFilter` properties must contain OpenVeo groups ids and not OpenVeo categories names.
Also note that the value of your `categoriesFilter` is not correct as it should contain the id of the OpenVeo taxonomy holding categories.

**Comment by Adsys12** [comment]
Hi Maxime,
Thank you for your answer.
To obtain the IDs of categories and groups we do openveo_url/taxonomies ?

![image](https://user-images.githubusercontent.com/89521201/130792222-386b7e7e-44b1-4168-88ec-576ea1b850c9.png)

**Comment by Adsys12** [comment]
Hello @maxime-beguin , thank you a lot for your support. But now if I upload a video on the portal, it is only visible after restarting the openveo portal service.
Do you have any idea about this?
